[project]
name = "gestion-taches-enseignants"
version = "0.1.0"
description = "Une application Flask pour la gestion des tâches d'enseignement."
authors = [
    {name = "Votre Nom", email = "vous@example.com"}
]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0.0",
    "psycopg2-binary>=2.9.9",
    "openpyxl>=3.1.0",
    "Flask-Login>=0.6.3",
    "werkzeug>=3.0.0",
]

[project.optional-dependencies]
dev = [
    "ruff", # Outil de linting et de formatage pour le développement.
]

# --- Configuration de Ruff (Linter et Formateur) ---
[tool.ruff]
# Répertoires source à analyser. "." signifie le répertoire courant.
src = ["."]

# Liste des répertoires et fichiers à exclure de l'analyse.
# Essentiel pour ignorer les environnements virtuels, caches, et autres.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Longueur maximale des lignes, respectée par le linter et le formateur.
line-length = 150

# Version de Python ciblée pour garantir la compatibilité des suggestions.
target-version = "py311" # Doit correspondre à `requires-python`.


# --- Configuration du Linter de Ruff ([tool.ruff.lint]) ---
[tool.ruff.lint]
# Sélection des catégories de règles à activer.
# E: Erreurs (Pyflakes)
# F: Flakes (logique erronée, variables inutilisées)
# W: Warnings de style (Pycodestyle)
# I: Organisation des imports (isort)
# UP: Suggestions de modernisation de la syntaxe (pyupgrade)
select = ["E", "F", "W", "I", "UP"]

# Règles spécifiques à ignorer si nécessaire.
# Par exemple, "E501" (ligne trop longue) est géré par le formateur.
# ignore = ["E501"]


# --- Configuration du Formateur de Ruff ([tool.ruff.format]) ---
[tool.ruff.format]
# Style de guillemets à utiliser pour les chaînes de caractères.
quote-style = "double"

# Style d'indentation à utiliser ("space" ou "tab").
indent-style = "space"

# `skip-magic-trailing-comma`: La valeur par défaut `false` est généralement
# recommandée pour la cohérence du formatage, notamment avec les virgules de fin.
# skip-magic-trailing-comma = false