[project]
name = "python-template" # Nom du projet (peut être personnalisé)
version = "0.1.0" # Version actuelle du projet
description = "Une application Flask pour la gestion des tâches enseignants." # Description concise du projet
authors = [
    {name = "Votre Nom", email = "vous@example.com"} # Informations sur l'auteur (à personnaliser)
]
requires-python = ">=3.11" # Version minimale de Python requise
dependencies = [
    "flask>=3.0.0", # Dépendance principale pour le framework web Flask (version mise à jour si possible)
    "psycopg2-binary>=2.9.9", # Connecteur PostgreSQL (binaire pour faciliter l'installation)
]

[project.optional-dependencies]
dev = [
    "ruff", # Outil de linting et formatage (pour le développement)
]

# --- Configuration de Ruff (Linter et Formateur) ---
[tool.ruff]
# Répertoires source à analyser par Ruff. "." signifie le répertoire courant.
src = ["."]

# Exclure les répertoires et fichiers typiquement non analysés.
# Utile pour éviter d'analyser les environnements virtuels, caches, builds, etc.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv", # Environnement virtuel Python standard
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules", # Dépendances JavaScript/Node.js
    "venv", # Autre nom commun pour l'environnement virtuel
    ".pythonlibs", # Utilisé par certains environnements comme Replit
]

# Longueur maximale des lignes (s'applique au linter et au formateur).
# 150 est assez permissif ; 88, 100 ou 120 sont aussi des choix courants.
line-length = 150

# Définir la version Python cible pour Ruff.
# Doit correspondre à votre `requires-python` pour assurer la compatibilité.
target-version = "py311" # Correspond à Python 3.11


# --- Configuration spécifique au Linter de Ruff ([tool.ruff.lint]) ---
[tool.ruff.lint]
# Règles de linter à activer.
# E: Erreurs Pyflakes (erreurs de syntaxe, noms non définis, etc.)
# F: Flakes Pyflakes (logique potentiellement erronée, variables non utilisées)
# W: Warnings Pycodestyle (erreurs de style, ex: E501 ligne trop longue)
# I: Isort (vérification et correction des imports)
# UP: Pyupgrade (suggestions pour moderniser la syntaxe Python)
select = ["E", "F", "W", "I", "UP"]

# Règles spécifiques à ignorer.
# Par exemple, si vous préférez gérer la longueur des lignes uniquement avec le formateur
# et non avec le linter, vous pourriez ignorer E501.
# Actuellement, aucune règle n'est ignorée globalement.
# ignore = ["E501"]

# Déclarer des variables globales que Ruff pourrait ne pas détecter,
# afin d'éviter des erreurs F821 (undefined name).
# Utile pour des variables injectées par des frameworks (ex: `g` et `request` de Flask dans les modules).
# `g` et `request` sont typiquement importés dans Flask, donc pas toujours nécessaire ici
# si les imports sont corrects dans chaque fichier.
# globals = [
#   "g",
#   "request" # Si utilisé sans import explicite dans certains contextes
# ]

# Configuration des règles "fixables" ou "non-fixables".
# Généralement, la configuration par défaut de Ruff est suffisante.
# fixable = ["A", "B"] # Sélectionne TOUTES les règles fixables des catégories A et B
# unfixable = []       # Empêche la correction automatique de certaines règles


# --- Configuration spécifique au Formateur de Ruff ([tool.ruff.format]) ---
[tool.ruff.format]
# Style de guillemets pour les chaînes de caractères.
# "double" -> "chaîne"
# "single" -> 'chaîne'
quote-style = "double"

# Type d'indentation : "space" ou "tab".
indent-style = "space" # Utilise des espaces pour l'indentation (taille définie par le linter/éditeur)

# `skip-magic-trailing-comma` (Commenté car la valeur par défaut `false` est souvent préférée)
# Si `true`, Ruff (formateur) ne supprime pas la virgule finale "magique" (trailing comma)
# dans les cas où elle pourrait rendre le formatage de f-strings multilignes complexe moins lisible.
# Laisser à `false` (défaut) est généralement bien pour la cohérence.
# skip-magic-trailing-comma = false