"""Initial schema creation

Revision ID: 82fb11542554
Revises: 
Create Date: 2025-06-18 01:39:12.956808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82fb11542554'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anneesscolaires',
    sa.Column('annee_id', sa.Integer(), nullable=False),
    sa.Column('libelle_annee', sa.String(), nullable=False),
    sa.Column('est_courante', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('annee_id'),
    sa.UniqueConstraint('libelle_annee')
    )
    with op.batch_alter_table('anneesscolaires', schema=None) as batch_op:
        batch_op.create_index('annee_courante_unique_idx', ['est_courante'], unique=True, postgresql_where=sa.text('est_courante IS true'))

    op.create_table('champs',
    sa.Column('champno', sa.String(), nullable=False),
    sa.Column('champnom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('champno')
    )
    op.create_table('typesfinancement',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_dashboard_only', sa.Boolean(), nullable=False),
    sa.CheckConstraint('NOT (is_admin AND is_dashboard_only)', name='users_role_exclusivity_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('champ_annee_statuts',
    sa.Column('champ_no', sa.String(), nullable=False),
    sa.Column('annee_id', sa.Integer(), nullable=False),
    sa.Column('est_verrouille', sa.Boolean(), nullable=False),
    sa.Column('est_confirme', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['annee_id'], ['anneesscolaires.annee_id'], ),
    sa.ForeignKeyConstraint(['champ_no'], ['champs.champno'], ),
    sa.PrimaryKeyConstraint('champ_no', 'annee_id')
    )
    op.create_table('cours',
    sa.Column('codecours', sa.String(), nullable=False),
    sa.Column('annee_id', sa.Integer(), nullable=False),
    sa.Column('champno', sa.String(), nullable=False),
    sa.Column('coursdescriptif', sa.String(), nullable=False),
    sa.Column('nbperiodes', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nbgroupeinitial', sa.Integer(), nullable=False),
    sa.Column('estcoursautre', sa.Boolean(), nullable=False),
    sa.Column('financement_code', sa.String(), nullable=True),
    sa.CheckConstraint('estcoursautre = false OR financement_code IS NULL', name='cours_financement_validation_check'),
    sa.CheckConstraint('nbgroupeinitial >= 0', name='cours_nbgroupeinitial_check'),
    sa.CheckConstraint('nbperiodes >= 0', name='cours_nbperiodes_check'),
    sa.ForeignKeyConstraint(['annee_id'], ['anneesscolaires.annee_id'], ),
    sa.ForeignKeyConstraint(['champno'], ['champs.champno'], ),
    sa.ForeignKeyConstraint(['financement_code'], ['typesfinancement.code'], ),
    sa.PrimaryKeyConstraint('codecours', 'annee_id')
    )
    op.create_table('enseignants',
    sa.Column('enseignantid', sa.Integer(), nullable=False),
    sa.Column('annee_id', sa.Integer(), nullable=False),
    sa.Column('nomcomplet', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('champno', sa.String(), nullable=False),
    sa.Column('esttempsplein', sa.Boolean(), nullable=False),
    sa.Column('estfictif', sa.Boolean(), nullable=False),
    sa.Column('peutchoisirhorschampprincipal', sa.Boolean(), nullable=False),
    sa.CheckConstraint('estfictif = true OR (nom IS NOT NULL AND prenom IS NOT NULL)', name='enseignants_nom_prenom_si_reel_check'),
    sa.ForeignKeyConstraint(['annee_id'], ['anneesscolaires.annee_id'], ),
    sa.ForeignKeyConstraint(['champno'], ['champs.champno'], ),
    sa.PrimaryKeyConstraint('enseignantid'),
    sa.UniqueConstraint('nom', 'prenom', 'annee_id', name='enseignants_nom_prenom_annee_id_key')
    )
    op.create_table('user_champ_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('champ_no', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['champ_no'], ['champs.champno'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'champ_no')
    )
    op.create_table('attributionscours',
    sa.Column('attributionid', sa.Integer(), nullable=False),
    sa.Column('enseignantid', sa.Integer(), nullable=False),
    sa.Column('codecours', sa.String(), nullable=False),
    sa.Column('annee_id_cours', sa.Integer(), nullable=False),
    sa.Column('nbgroupespris', sa.Integer(), nullable=False),
    sa.CheckConstraint('nbgroupespris > 0', name='attributionscours_nbgroupespris_check'),
    sa.ForeignKeyConstraint(['codecours', 'annee_id_cours'], ['cours.codecours', 'cours.annee_id'], ),
    sa.ForeignKeyConstraint(['enseignantid'], ['enseignants.enseignantid'], ),
    sa.PrimaryKeyConstraint('attributionid')
    )
    op.create_table('preparation_horaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annee_id', sa.Integer(), nullable=False),
    sa.Column('secondaire_level', sa.Integer(), nullable=False),
    sa.Column('codecours', sa.String(), nullable=False),
    sa.Column('annee_id_cours', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('colonne_assignee', sa.String(), nullable=False),
    sa.CheckConstraint('secondaire_level >= 1 AND secondaire_level <= 5', name='preparation_horaire_secondaire_level_check'),
    sa.ForeignKeyConstraint(['annee_id'], ['anneesscolaires.annee_id'], ),
    sa.ForeignKeyConstraint(['codecours', 'annee_id_cours'], ['cours.codecours', 'cours.annee_id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.enseignantid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annee_id', 'secondaire_level', 'enseignant_id', 'colonne_assignee', name='preparation_horaire_unique_assignment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preparation_horaire')
    op.drop_table('attributionscours')
    op.drop_table('user_champ_access')
    op.drop_table('enseignants')
    op.drop_table('cours')
    op.drop_table('champ_annee_statuts')
    op.drop_table('users')
    op.drop_table('typesfinancement')
    op.drop_table('champs')
    with op.batch_alter_table('anneesscolaires', schema=None) as batch_op:
        batch_op.drop_index('annee_courante_unique_idx', postgresql_where=sa.text('est_courante IS true'))

    op.drop_table('anneesscolaires')
    # ### end Alembic commands ###
